import { describe, expect, it } from "vitest";
import { evaluateExpression, truthy } from "../src/expressions/expr";
// From the INSTALLED package, not a sibling checkout. The conformance repo's
// own runner README records why: its two older parity harnesses hard-coded
// `../../<repo>/src/`, so they worked in one directory layout and silently
// no-op'd everywhere else — including CI, which checks out one repo.
import CASES from "@particle-academy/fancy-conformance/suites/shared/expr/cases.json" with { type: "json" };

/**
 * The PHP/TS parity table for `{{ }}` resolution, run against THIS side.
 *
 * `fancy-flow-php` runs the identical file. That is the whole mechanism: the
 * two runtimes read the same rows, so a divergence is a red build in whichever
 * one drifted rather than a support ticket six months later.
 *
 * ## Why this suite did not exist until now
 *
 * `@particle-academy/fancy-conformance` shipped three suites and — worth saying
 * plainly — **nothing consumed it**. No repo listed it as a dependency; the one
 * apparent consumer references it in a code COMMENT saying its goldens "were
 * generated by" the package. So no suite of its ran in anyone's CI.
 *
 * And even a perfect expression suite could not have caught the actual gap.
 * Conformance compares two implementations; `Expr` had no TypeScript twin at
 * all, and a fixture table is structurally unable to fail on ABSENCE. It can
 * only report that two things disagree, never that one is missing.
 *
 * This file is both halves of the fix: the suite exists, and it runs.
 */
type Case = {
  id: string;
  title: string;
  fn: string;
  input: Record<string, unknown>;
  expected: unknown;
  skip?: boolean;
};

const cases = (CASES as { cases: Case[] }).cases.filter((c) => !c.skip);

const FNS: Record<string, (input: Record<string, unknown>) => unknown> = {
  evaluateExpression: (i) =>
    evaluateExpression(i.template, (i.context ?? {}) as Record<string, unknown>),
  truthy: (i) => truthy(i.value),
};

describe("conformance: shared/expr", () => {
  it("has cases, and every one names a function this runner implements", () => {
    // The vacuity guard. A renamed `fn`, or a suite that failed to load, would
    // otherwise make the table below pass over an empty list.
    expect(cases.length).toBeGreaterThan(15);
    for (const c of cases) {
      expect(FNS[c.fn], `case ${c.id} calls unimplemented fn "${c.fn}"`).toBeTypeOf("function");
    }
  });

  it.each(cases.map((c) => [c.id, c.title, c] as const))("%s %s", (_id, _title, c) => {
    expect(FNS[c.fn]!(c.input)).toEqual(c.expected);
  });
});
